#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

SUBCOMMANDS_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/subcommands"

case "$1" in
  cassandra:admin-console | cassandra:app-links | cassandra:clone | cassandra:connect | \
    cassandra:create | cassandra:destroy | cassandra:enter | cassandra:exists | \
    cassandra:export | cassandra:expose | cassandra:import | cassandra:info | \
    cassandra:link | cassandra:linked | cassandra:links | cassandra:list | \
    cassandra:logs | cassandra:pause | cassandra:promote | cassandra:restart | \
    cassandra:set | cassandra:start | cassandra:stop | cassandra:unexpose | \
    cassandra:unlink | cassandra:upgrade)
    SUBCOMMAND="${1#cassandra:}"
    exec "$SUBCOMMANDS_PATH/$SUBCOMMAND" "$@"
    ;;

  help | cassandra:help)
    cat <<help_desc
    cassandra:admin-console <service>, open a cqlsh shell against the service (alias of connect)
    cassandra:app-links <app>, list all cassandra service links for a given app
    cassandra:clone <service> <new-service> [--clone-flags...], create container <new-name> then copy data from <name> into <new-name>
    cassandra:connect <service>, connect to the service via cqlsh
    cassandra:create <service> [--create-flags...], create a cassandra service
    cassandra:destroy <service> [-f|--force], delete the cassandra service/data/container if there are no links left
    cassandra:enter <service>, enter or run a command in a running cassandra service container
    cassandra:exists <service>, check if the cassandra service exists
    cassandra:export <service>, export a snapshot of the cassandra service data directory
    cassandra:expose <service> <ports...>, expose a cassandra service on custom host:port
    cassandra:import <service>, import a snapshot into the cassandra service data directory
    cassandra:info <service> [--single-info-flag], print the service information
    cassandra:link <service> <app> [--link-flags...], link the cassandra service to the app
    cassandra:linked <service> <app>, check if the cassandra service is linked to an app
    cassandra:links <service>, list all apps linked to the cassandra service
    cassandra:list, list all cassandra services
    cassandra:logs <service> [-t|--tail] <tail-num-optional>, print the most recent log(s) for this service
    cassandra:pause <service>, pause a running cassandra service
    cassandra:promote <service> <app>, promote service <service> as CASSANDRA_URL in <app>
    cassandra:restart <service>, graceful shutdown and restart of the cassandra service container
    cassandra:set <service> <key> <value>, set or clear a property for a service
    cassandra:start <service>, start a previously stopped cassandra service
    cassandra:stop <service>, stop a running cassandra service
    cassandra:unexpose <service>, unexpose a previously exposed cassandra service
    cassandra:unlink <service> <app>, unlink the cassandra service from the app
    cassandra:upgrade <service> [--upgrade-flags...], upgrade service <service> to the specified image/version
help_desc
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;
esac
