#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-admin-console-cmd() {
  declare desc="alias of $PLUGIN_COMMAND_PREFIX:connect"
  local cmd="$PLUGIN_COMMAND_PREFIX:admin-console" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"

  verify_service_name "$SERVICE"
  service_connect "$SERVICE"
}

service-admin-console-cmd "$@"
