#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-export-cmd() {
  declare desc="export a snapshot of the $PLUGIN_SERVICE service data directory"
  local cmd="$PLUGIN_COMMAND_PREFIX:export" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"

  verify_service_name "$SERVICE"
  service_export "$SERVICE"
}

service-export-cmd "$@"
