#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-links-cmd() {
  declare desc="list all apps linked to the $PLUGIN_SERVICE service"
  local cmd="$PLUGIN_COMMAND_PREFIX:links" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"

  verify_service_name "$SERVICE"
  service_links "$SERVICE"
}

service-links-cmd "$@"
