#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-promote-cmd() {
  declare desc="promote service <service> as CASSANDRA_URL in <app>"
  local cmd="$PLUGIN_COMMAND_PREFIX:promote" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1" APP="$2"

  verify_service_name "$SERVICE"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"
  service_promote "$SERVICE" "$APP"
  dokku_log_info2 "$PLUGIN_SERVICE service $SERVICE promoted in $APP"
}

service-promote-cmd "$@"
