#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-restart-cmd() {
  declare desc="graceful shutdown and restart of the $PLUGIN_SERVICE service container"
  local cmd="$PLUGIN_COMMAND_PREFIX:restart" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"

  verify_service_name "$SERVICE"
  service_container_rm "$SERVICE"
  service_create_container "$SERVICE"
}

service-restart-cmd "$@"
