#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-stop-cmd() {
  declare desc="stop a running $PLUGIN_SERVICE service and remove the running container"
  local cmd="$PLUGIN_COMMAND_PREFIX:stop" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"

  verify_service_name "$SERVICE"
  service_container_rm "$SERVICE"
  dokku_log_info2 "$PLUGIN_SERVICE container stopped: $SERVICE"
}

service-stop-cmd "$@"
